const IPC_CHANNELS = {
  OPEN_FOLDER_DIALOG: 'OPEN_FOLDER_DIALOG',
  GET_IMAGE_TAGS: 'GET_IMAGE_TAGS',
  CHECK_IMAGE_EXISTS: 'CHECK_IMAGE_EXISTS',
  ATTACH_SHELL: 'ATTACH_SHELL',
  SAVE_SETTINGS: 'SAVE_SETTINGS'
};

const ALL_SETTINGS = 'all-settings';
const WIN_DIMENSION = 'WIN_DIMENSION';

module.exports = { IPC_CHANNELS, ALL_SETTINGS, WIN_DIMENSION };
