const IPC_CHANNELS = {
  OPEN_FOLDER_DIALOG: 'OPEN_FOLDER_DIALOG',
  GET_IMAGE_TAGS: 'GET_IMAGE_TAGS',
  CHECK_IMAGE_EXISTS: 'CHECK_IMAGE_EXISTS',
  ATTACH_SHELL: 'ATTACH_SHELL'
};

module.exports = { IPC_CHANNELS };
