name: envase-ci

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macos-12
    strategy:
      matrix:
        node_version: [10]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Setup Apple code signing
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Generate Icons
        run: npm run generate-icons

      - name: Bundle UI
        run: npm run build-react
        env:
          REACT_APP_GA_ID: ${{ secrets.GA_ID }}
          REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Build & Release for mac
        run: npm run build-mac -- --publish onTagOrDraft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Release for windows
        run: npm run build-win -- --publish onTagOrDraft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Release for linux
        run: npm run build-linux -- --publish onTagOrDraft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
