name: envase-ci

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macos-10.15
    strategy:
      matrix:
        node_version: [10]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Generate Icons
        run: yarn generate-icons

      - name: Buile React
        run: yarn build-react

      - name: Build & Release for mac
        run: yarn build-mac --publish onTagOrDraft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Release for windows
        run: yarn build-win --publish onTagOrDraft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Release for linux
        run: yarn build-linux --publish onTagOrDraft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
